services:
  learning:
    container_name: learning
    build:
      context: .
      args:
        NODE_ENV: production
        NEXT_PUBLIC_GRAPHQL_URL: https://api.epess.org/v1/graphql
        NEXT_PUBLIC_LIVEKIT_URL: https://meet.epess.org
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_aW4tY2hpbXAtOTcuY2xlcmsuYWNjb3VudHMuZGV2JA
      CLERK_SECRET_KEY: sk_test_sA5lsb1GHwUNXWQCp5ev70QkaoF5EmdAHNWiCGwZF6
      NEXT_PUBLIC_GRAPHQL_URL: https://api.epess.org/v1/graphql
      LIVEKIT_API_KEY: API9imca9hBiQ7w
      LIVEKIT_API_SECRET: 75bhDbSrTpBTjWpcYRDM0fCAdcjHi3u6OFVNJe9Acx0
      NEXT_PUBLIC_LIVEKIT_URL: https://meet.epess.org
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: /auth/sign-in
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: /auth/sign-up
    ports:
      - 5203:3000
    networks:
      - epess-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.learning.rule=Host(`learning.epess.org`)
networks:
  epess-net:
    driver: bridge
    external: true
